version: "3"

networks:
    default:
        external:
            name: webproxy
services:
  calibre:
    image: linuxserver/calibre
    expose:
      - 8080
      - 8081
    environment:
      - TZ=Europe/Paris
      - GUAC_USER=${GUAC_USER}
      - GUAC_PASS=${GUAC_PASS}
    labels:
      # Books is the actual calibre public web interface
      - traefik.http.routers.calibre-web-legacy.rule=Host(`calibre-web.davidfain.com`,`calibre-web.davidfain.fr`)
      - traefik.http.routers.calibre-web-legacy.service=calibre-web-legacy
      - traefik.http.services.calibre-web-legacy.loadbalancer.server.port=8081
      - traefik.http.routers.calibre-web-legacy.tls=true
      - traefik.http.routers.calibre-web-legacy.tls.certresolver=le
      # Calibre is the protected backend
      - traefik.http.routers.calibre.rule=Host(`calibre.davidfain.com`,`calibre.davidfain.fr`)
      - traefik.http.routers.calibre.service=calibre
      - traefik.http.services.calibre.loadbalancer.server.port=8080
      - traefik.http.routers.calibre.tls=true
      - traefik.http.routers.calibre.tls.certresolver=le
    volumes:
      - /mnt/raid/0.SHARED/3.Books/:/config
    restart: unless-stopped
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - TZ=Europe/Paris
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    labels:
      # Books is the actual calibre public web interface
      - traefik.http.routers.calibre-web-ui.rule=Host(`books.davidfain.com`,`books.davidfain.fr`)
      - traefik.http.routers.calibre-web-ui.service=calibre-web-ui
      - traefik.http.services.calibre-web-ui.loadbalancer.server.port=8083
      - traefik.http.routers.calibre-web-ui.tls=true
      - traefik.http.routers.calibre-web-ui.tls.certresolver=le
    volumes:
      - ./web-data/:/config
      - /mnt/raid/0.SHARED/3.Books/Calibre Library/:/books
    ports:
      - 8083:8083
    restart: unless-stopped